### ISSUE TITLE
Occasional error when using with tessera

### ISSUE THREAD

**Issue by JesseCrocker** [mojodna/tilelive-tmstyle#13]
Im running tessera with 12 sources in a config file, and 3 of which use tilelive-tmstyle, sometimes tessera fails on launch, and sometimes it happens multiple times in a row, with an error that seems to either be an issue in tilelive-tmstyle, or maybe in carto.

Output from tessera
```
Listening at http://0.0.0.0:8080
/opt/tessera/server.js:111
          throw err;
          ^

TypeError: Cannot read property 'class' of undefined
    at Renderer.render (/opt/tessera/node_modules/tilelive-tmstyle/node_modules/carto/lib/carto/renderer.js:117:25)
    at /opt/tessera/node_modules/tilelive-tmstyle/index.js:210:52
    at Immediate._onImmediate (/opt/tessera/node_modules/tilelive-cache/node_modules/locking-cache/index.js:74:25)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

**Comment by JesseCrocker** [comment]
Turns out this is not in this module.
